In [1]:
import numpy as np

In [6]:
from numpy import *

# Array

In [7]:
arr1 = array([2,4,6,8])
            
print(arr1)

[2 4 6 8]


In [8]:
# 2 D array
arr2 = array([
            [1,2,3],
            [4,5,6]
])

print(arr2)

[[1 2 3]
 [4 5 6]]


In [9]:
print(arr2.ndim)

2


In [10]:
print(arr2.shape)

(2, 3)


In [11]:
print(arr2.size)

6


In [12]:
# How to convert 2D array into 1 D array
arr3 = arr2.flatten()
print(arr3)
arr4 = arr2.reshape(3,2)
print(arr4)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [14]:
a1 = array([
            [1,2,3,6,2,9],
            [4,5,6,7,5,3]
])
a2 = a1.flatten()
a3 = a2.reshape(3,4)
print(a3)

[[1 2 3 6]
 [2 9 4 5]
 [6 7 5 3]]


In [15]:
# To create 3D array
a4 = a2.reshape(2,2,3)
a4

array([[[1, 2, 3],
        [6, 2, 9]],

       [[4, 5, 6],
        [7, 5, 3]]])

# Matrix

In [16]:
b1 =  array([
            [1,2,3,6],
            [4,5,6,7]
])
# To convert array to matrix
m = matrix(b1)
print(m)

[[1 2 3 6]
 [4 5 6 7]]


In [17]:
# Though matrix and array output sees similar but we can perform more operations on matrix

# Another way of creating matrix

m2 = matrix('1 2 3 4; 5 6 7 8')
m2

matrix([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [18]:
# To create multiple rows and columns i.e. 4 rows and 2 columns

m3 = matrix('1 2; 3 4; 5 6; 7 8')
m3

matrix([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [19]:
m4 = matrix('1 2 3; 4 5 6; 7 8 9')
m4

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [21]:
# Digonal elements.
print(diagonal(m4))

[1 5 9]


In [22]:
# To find the minimum element
print(m4.min())

1


In [23]:
# To find the max element
print(m4.max())

9


In [24]:
# Adding and multiply the matrix
n1 = matrix('1 2 3; 4 5 6; 7 8 9')
n2 = matrix('1 2 3; 4 5 6; 7 8 9')

n3 = n1 + n2
n3

matrix([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]])

In [25]:
n4 = n1 * n2
n4

matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])