# 1. Write a program to multiply M x N matrix by N x A matrix and
# create a real matrix product

In [18]:
import numpy as np
m = int(input('Enter value of M :'))
n = int(input('Enter value of N :'))
a = int(input('Enter value of A :'))

Enter value of M :5
Enter value of N :3
Enter value of A :2


In [19]:
first_matrix = np.arange(1, (m*n)+1).reshape(m,n)
first_matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [20]:
second_matrix = np.arange(1, (n*a)+1).reshape(n,a)
second_matrix

array([[1, 2],
       [3, 4],
       [5, 6]])

# Dot product of 2 matrices

In [21]:
dot_product = first_matrix.dot(second_matrix)
dot_product

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100],
       [103, 136],
       [130, 172]])