# Random numbers in numpy

### np.random.random()¶
#### generates a random number from 0 to 1

In [1]:
import numpy as np

In [2]:
print(np.random.random())

0.4405365774657358


In [3]:
print(np.random.random())
print(np.random.random())
print(np.random.random())
print(np.random.random())

0.1865684645946858
0.24675422721158913
0.9726677828306193
0.7713932486864814


### np.random.seed()
random value will not change every time

In [4]:
np.random.seed(10)              # 10 is just number, we can use any other number as well
print(np.random.random())
print(np.random.random())
print(np.random.random())
print(np.random.random())

0.771320643266746
0.0207519493594015
0.6336482349262754
0.7488038825386119


In [5]:
np.random.seed(10)              
print(np.random.random())
print(np.random.random())
print(np.random.random())
print(np.random.random())

0.771320643266746
0.0207519493594015
0.6336482349262754
0.7488038825386119


In [6]:
# you can specify the shape
x = np.random.random((4, 4))
x

array([[0.49850701, 0.22479665, 0.19806286, 0.76053071],
       [0.16911084, 0.08833981, 0.68535982, 0.95339335],
       [0.00394827, 0.51219226, 0.81262096, 0.61252607],
       [0.72175532, 0.29187607, 0.91777412, 0.71457578]])

### np.random.randint()

In [7]:
num = np.random.randint(low = 20, high =100) #range
num

33

In [8]:
num = np.random.randint(low = 20, high =100,size = 5) # 5 different values
num

array([45, 33, 50, 50, 32])

In [9]:
num = np.random.randint(low = 20, high =100,size = (5,5)) #5,5 shape
num

array([[85, 51, 77, 56, 47],
       [38, 97, 42, 43, 31],
       [48, 94, 29, 35, 38],
       [91, 31, 37, 66, 27],
       [95, 48, 53, 64, 25]])

### np.random.choice(list_of_choice,num_of_ele)

In [10]:
a = [24,27,22,47,35,82,-33,25,2.3,18]
a

[24, 27, 22, 47, 35, 82, -33, 25, 2.3, 18]

In [11]:
np.random.choice(a,size = 3)

array([35. , 25. ,  2.3])

In [12]:
np.random.choice(a,size = (5,5))

array([[  2.3,  22. , -33. ,  22. ,   2.3],
       [  2.3, -33. , -33. ,  82. , -33. ],
       [ 24. ,  24. , -33. ,  18. ,  27. ],
       [  2.3,  18. ,  27. ,  22. ,   2.3],
       [ 18. ,  18. ,  82. ,  24. ,  22. ]])

### Other Important functions

In [13]:
x = np.random.random((4, 4))
x

array([[0.12697184, 0.07979268, 0.2350386 , 0.65996495],
       [0.21495319, 0.20304662, 0.38286511, 0.2248728 ],
       [0.1146488 , 0.58301705, 0.23264106, 0.55651819],
       [0.52381088, 0.35095822, 0.70533161, 0.82070374]])

### np.round()
rounds an array to given number of decimals

In [14]:
# to round it to 3 decimal points
rounded = np.round(x, 3)
rounded

array([[0.127, 0.08 , 0.235, 0.66 ],
       [0.215, 0.203, 0.383, 0.225],
       [0.115, 0.583, 0.233, 0.557],
       [0.524, 0.351, 0.705, 0.821]])

In [15]:
new = rounded * 100
new

array([[12.7,  8. , 23.5, 66. ],
       [21.5, 20.3, 38.3, 22.5],
       [11.5, 58.3, 23.3, 55.7],
       [52.4, 35.1, 70.5, 82.1]])

### astype()
to change the data type of elements

In [16]:
# to change the data type of elements to integers
intt = new.astype(int)
intt

array([[12,  8, 23, 66],
       [21, 20, 38, 22],
       [11, 58, 23, 55],
       [52, 35, 70, 82]])

In [17]:
# to change the data type of elements to float
flt = intt.astype(float)
flt

array([[12.,  8., 23., 66.],
       [21., 20., 38., 22.],
       [11., 58., 23., 55.],
       [52., 35., 70., 82.]])

### reshape()
to reshape an array.

In [19]:
x = np.arange(32)#(1,32) by default
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [20]:
x.shape

(32,)

In [21]:
x = x.reshape(4,8)# multiplication should be32 because there are 32 data available in array
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [22]:
x.shape

(4, 8)

In [23]:
x = x.reshape(8,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [24]:
x.shape

(8, 4)

In [25]:
x = x.reshape(2,4,4)# 2 main matrix, 4 row n 4 column.
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]]])

In [26]:
# to reduce ndarray to 1d array
x = x.reshape(-1)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [27]:
# you know you want 4 rows and not sure about how many columns will be there
x.reshape(4,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [28]:
# you know you want 4 columns and not sure about how many rows will be there
x.reshape(-1,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

# Some Other Mathematical operations on np arrays

In [29]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
#np.sin()
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [31]:
#np.cos()
np.cos(a)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [32]:
#np.tan()
np.tan(a)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566])

In [33]:
#to get the exponential values i,e., e^num
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [34]:
#creating and reshaping the array
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### np.sum()
to get the sum of all the elements

In [35]:
np.sum(a)

45

In [36]:
# along the column
np.sum(a,axis = 0)

array([12, 15, 18])

In [37]:
# along the row
np.sum(a,axis = 1)

array([ 6, 15, 24])

## Transpose

In [38]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
b = a.T
b

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [40]:
# dot product
np.dot(a,b)

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [41]:
# to get the maximum element
a = np.array([1,4,2,6,10,13,5,7,3])
a

array([ 1,  4,  2,  6, 10, 13,  5,  7,  3])

In [42]:
a.max()

13

In [43]:
# to get the index at which the maximum element is present
a.argmax()

5

In [44]:
a

array([ 1,  4,  2,  6, 10, 13,  5,  7,  3])

In [45]:
#to sort the elements
np.sort(a)

array([ 1,  2,  3,  4,  5,  6,  7, 10, 13])

In [46]:
np.argsort(a)

array([0, 2, 8, 1, 6, 3, 7, 4, 5], dtype=int64)